export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const FETCH_IMAGE_CONFIG_REQUEST = "FETCH_IMAGE_CONFIG_REQUEST";
export const FETCH_IMAGE_CONFIG_SUCCESS = "FETCH_IMAGE_CONFIG_SUCCESS";
export const FETCH_IMAGE_CONFIG_FAILURE = "FETCH_IMAGE_CONFIG_FAILURE";